# This is a basic workflow to help you get started with Actions

name: success and failure

on:
  push:
  workflow_dispatch:

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  bad:
    runs-on: ubuntu-latest
    steps:
      - name: Live
        run: exit 0

  dependent:
    runs-on: ubuntu-latest
    needs:
    - ok
    - bad
    if: failure()
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
